# Generated by Django 3.2.9 on 2021-12-01 00:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, upload_to='images/')),
                ('country_of_origin', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('number_of_votes', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealRecommendTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MealRecommendRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('dete_of_rating', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealrecommend.mealrecommend')),
            ],
        ),
        migrations.AddField(
            model_name='mealrecommend',
            name='tags',
            field=models.ManyToManyField(to='mealrecommend.MealRecommendTag'),
        ),
        migrations.AddField(
            model_name='mealrecommend',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
