# Generated by Django 3.2.9 on 2021-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date_added',
            field=models.DateTimeField(default=1637356563.0872884),
        ),
        migrations.AlterField(
            model_name='meal',
            name='number_of_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mealrating',
            name='dete_of_rating',
            field=models.DateTimeField(default=1637356563.0882885),
        ),
    ]
