# Generated by Django 3.2.9 on 2021-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20211119_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='typical_mealtime',
            field=models.IntegerField(choices=[(1, 'morning'), (2, 'afternoon'), (3, 'evening')]),
        ),
        migrations.AlterField(
            model_name='mealrating',
            name='dete_of_rating',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
