# Generated by Django 3.2.9 on 2021-11-25 06:03

from django.db import migrations
import meals.models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20211122_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrating',
            name='dete_of_rating',
            field=meals.models.CustomDateTimeField(auto_now=True),
        ),
    ]
